version: 2.1

jobs:
  tests:
    docker:
      - image: circleci/node:14.18.0
    steps:
      - checkout
      - run:
          name: Running Tests
          command: npm test
  restore-caching:
    docker:
      - image: circleci/node:14.18.0
    steps:
      - checkout
      - restore_cache:
          keys:
            # Find a cache corresponding to this specific package-lock.json
            - v1-npm-deps-{{ checksum "package.json" }}
            # Fallback cache to be used
            - v1-npm-deps-

  build-and-deploy-to-firebase:
    docker:
      - image: circleci/node:14.18.0
    steps:
      - checkout
      - run:
          name: Building Production Ready Code
          command: npm install && CI=false npm run build
      - run:
          name: Deploy to Firebase
          command: ./node_modules/.bin/firebase deploy --token "$FIREBASE_TOKEN" --project=firebase-project-0509 --only hosting

  save-cache:
    docker:
      - image: circleci/node:14.18.0
    steps:
      - checkout
      - save_cache:
          key: v1-npm-deps-{{ checksum "package-lock.json" }}
          paths:
            - ./node_modules

workflows:
  version: 2
  firebase-workflow:
    jobs:
      - restore-caching
      - build-and-deploy-to-firebase:
          requires:
            - tests
          filters:
            branches:
              only:
                - develop
      - save-cache:
          requires:
            - build-and-deploy-to-firebase
